# SPDX-FileCopyrightText: 2025 The Despair Authors
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025 The Despair Authors
# SPDX-License-Identifier: MIT
site_name: Despair Edge Detection
docs_dir: docs
site_dir: site
nav:
  - Home: index.md
