from PyQt6.QtWidgets import QMainWindow

from processing.batch_processor import BatchProcessor

class EdgeDetectionApp(QMainWindow):  # type: ignore[misc]
    processor_thread: BatchProcessor | None

    def __init__(self) -> None: ...
    def init_ui(self) -> None: ...
    def select_folder(self) -> None: ...
    def process_folder(self, folder_path: str) -> None: ...
    def update_progress(self, value: int) -> None: ...
    def update_current_file(self, filename: str) -> None: ...
    def processing_finished(self) -> None: ...
