name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Mypy
        run: mypy --config-file mypy.ini .
      - name: Tests
        run: |
          pytest --maxfail=1 --disable-warnings
          pytest --cov=. --cov-config=.coveragerc --cov-fail-under=95
      - name: Bandit
        run: bandit -r . -ll -o bandit.html -f html
      - name: Pip audit
        run: pip-audit -r requirements.txt
      - name: License compliance
        run: reuse lint
      - name: Build docs
        run: mkdocs build --strict
      - name: Codespell
        run: codespell
      - name: Pip check
        run: pip check
      - name: Smoke test
        run: python smoke.py
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov
        if: always()
      - uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit.html
        if: always()
