# SPDX-FileCopyrightText: 2025 The Despair Authors
# SPDX-License-Identifier: MIT
name: CI
on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit pytest pip-audit reuse mkdocs codespell
      - name: Pre-commit
        run: pre-commit run --all-files
      - name: Tests
        run: pytest -q
      - name: Pip Audit
        run: pip-audit --severity-level high
      - name: REUSE lint
        run: reuse lint
      - name: Codespell
        run: codespell --ignore-words-list="nd" --skip=".git,venv"
      - name: Build docs
        run: mkdocs build --strict
      - name: Smoke test
        run: python smoke.py
